/* eslint-disable max-lines */
import type { Asset, Reading, DashboardStats, AssetStatus, Parameter } from "@/types/iot";

export const mockStats: DashboardStats = {
  totalAssets: 12,
  onlineAssets: 9,
  offlineAssets: 3,
  activeAlerts: 2,
};

export const mockAssets: Asset[] = [
  {
    id: 1,
    organizationId: "org_123",
    name: "Water Treatment Plant A",
    type: "Treatment Facility",
    location: "North District",
    status: 1 as AssetStatus,
    lastSeen: new Date(Date.now() - 5 * 60000).toISOString(),
    manufacturer: "AquaTech",
    modelNumber: "WTP-2000",
    sensors: [
      {
        id: 101,
        assetId: 1,
        name: "pH Sensor",
        parameter: 1 as Parameter,
        unit: "pH",
        thresholdLow: 6.5,
        thresholdHigh: 8.5,
        isActive: true,
      },
      {
        id: 102,
        assetId: 1,
        name: "Chlorine Monitor",
        parameter: 2 as Parameter,
        unit: "mg/L",
        thresholdLow: 0.5,
        thresholdHigh: 2.0,
        isActive: true,
      },
      {
        id: 103,
        assetId: 1,
        name: "Turbidity Sensor",
        parameter: 10 as Parameter,
        unit: "NTU",
        thresholdHigh: 5,
        isActive: true,
      },
    ],
  },
  {
    id: 2,
    organizationId: "org_123",
    name: "Pump Station 5",
    type: "Pump Station",
    location: "East District",
    status: 1 as AssetStatus,
    lastSeen: new Date(Date.now() - 2 * 60000).toISOString(),
    manufacturer: "FlowTech",
    modelNumber: "PS-500",
    sensors: [
      {
        id: 201,
        assetId: 2,
        name: "Flow Rate",
        parameter: 20 as Parameter,
        unit: "L/min",
        thresholdLow: 100,
        thresholdHigh: 500,
        isActive: true,
      },
      {
        id: 202,
        assetId: 2,
        name: "Pressure Sensor",
        parameter: 21 as Parameter,
        unit: "bar",
        thresholdLow: 2,
        thresholdHigh: 8,
        isActive: true,
      },
    ],
  },
  {
    id: 3,
    organizationId: "org_123",
    name: "Storage Tank B",
    type: "Storage",
    location: "Central District",
    status: 1 as AssetStatus,
    lastSeen: new Date(Date.now() - 10 * 60000).toISOString(),
    sensors: [
      {
        id: 301,
        assetId: 3,
        name: "Level Sensor",
        parameter: 22 as Parameter,
        unit: "m",
        thresholdLow: 2,
        thresholdHigh: 10,
        isActive: true,
      },
      {
        id: 302,
        assetId: 3,
        name: "Temperature",
        parameter: 11 as Parameter,
        unit: "°C",
        thresholdLow: 5,
        thresholdHigh: 25,
        isActive: true,
      },
    ],
  },
  {
    id: 4,
    organizationId: "org_123",
    name: "Filtration Unit 3",
    type: "Filtration",
    location: "South District",
    status: 1 as AssetStatus,
    lastSeen: new Date(Date.now() - 1 * 60000).toISOString(),
    sensors: [
      {
        id: 401,
        assetId: 4,
        name: "Turbidity",
        parameter: 10 as Parameter,
        unit: "NTU",
        thresholdHigh: 3,
        isActive: true,
      },
      {
        id: 402,
        assetId: 4,
        name: "Flow Rate",
        parameter: 20 as Parameter,
        unit: "L/min",
        thresholdLow: 50,
        thresholdHigh: 300,
        isActive: true,
      },
    ],
  },
  {
    id: 5,
    organizationId: "org_123",
    name: "Monitoring Station 7",
    type: "Monitoring",
    location: "West District",
    status: 2 as AssetStatus,
    lastSeen: new Date(Date.now() - 120 * 60000).toISOString(),
    sensors: [
      {
        id: 501,
        assetId: 5,
        name: "Dissolved Oxygen",
        parameter: 5 as Parameter,
        unit: "mg/L",
        thresholdLow: 5,
        isActive: false,
      },
      {
        id: 502,
        assetId: 5,
        name: "Conductivity",
        parameter: 12 as Parameter,
        unit: "μS/cm",
        thresholdHigh: 1500,
        isActive: false,
      },
    ],
  },
  {
    id: 6,
    organizationId: "org_123",
    name: "Treatment Plant C",
    type: "Treatment Facility",
    location: "North District",
    status: 1 as AssetStatus,
    lastSeen: new Date(Date.now() - 3 * 60000).toISOString(),
    sensors: [
      {
        id: 601,
        assetId: 6,
        name: "pH Monitor",
        parameter: 1 as Parameter,
        unit: "pH",
        thresholdLow: 6.5,
        thresholdHigh: 8.5,
        isActive: true,
      },
      {
        id: 602,
        assetId: 6,
        name: "Free Chlorine",
        parameter: 2 as Parameter,
        unit: "mg/L",
        thresholdLow: 0.5,
        thresholdHigh: 2.0,
        isActive: true,
      },
    ],
  },
  {
    id: 7,
    organizationId: "org_123",
    name: "Pump Station 12",
    type: "Pump Station",
    location: "East District",
    status: 1 as AssetStatus,
    lastSeen: new Date(Date.now() - 7 * 60000).toISOString(),
    sensors: [
      {
        id: 701,
        assetId: 7,
        name: "Pressure",
        parameter: 21 as Parameter,
        unit: "bar",
        thresholdLow: 2,
        thresholdHigh: 8,
        isActive: true,
      },
    ],
  },
  {
    id: 8,
    organizationId: "org_123",
    name: "Reservoir D",
    type: "Storage",
    location: "Central District",
    status: 3 as AssetStatus,
    lastSeen: new Date(Date.now() - 30 * 60000).toISOString(),
    sensors: [
      {
        id: 801,
        assetId: 8,
        name: "Water Level",
        parameter: 22 as Parameter,
        unit: "m",
        thresholdLow: 3,
        thresholdHigh: 12,
        isActive: true,
      },
    ],
  },
  {
    id: 9,
    organizationId: "org_123",
    name: "Quality Monitor 4",
    type: "Monitoring",
    location: "South District",
    status: 1 as AssetStatus,
    lastSeen: new Date(Date.now() - 4 * 60000).toISOString(),
    sensors: [
      {
        id: 901,
        assetId: 9,
        name: "TDS Sensor",
        parameter: 13 as Parameter,
        unit: "ppm",
        thresholdHigh: 500,
        isActive: true,
      },
      {
        id: 902,
        assetId: 9,
        name: "Temperature",
        parameter: 11 as Parameter,
        unit: "°C",
        thresholdLow: 5,
        thresholdHigh: 25,
        isActive: true,
      },
    ],
  },
  {
    id: 10,
    organizationId: "org_123",
    name: "Pump Station 8",
    type: "Pump Station",
    location: "West District",
    status: 2 as AssetStatus,
    lastSeen: new Date(Date.now() - 180 * 60000).toISOString(),
    sensors: [
      {
        id: 1001,
        assetId: 10,
        name: "Flow Meter",
        parameter: 20 as Parameter,
        unit: "L/min",
        thresholdLow: 100,
        thresholdHigh: 400,
        isActive: false,
      },
    ],
  },
  {
    id: 11,
    organizationId: "org_123",
    name: "Filtration Unit 7",
    type: "Filtration",
    location: "North District",
    status: 1 as AssetStatus,
    lastSeen: new Date(Date.now() - 6 * 60000).toISOString(),
    sensors: [
      {
        id: 1101,
        assetId: 11,
        name: "Turbidity Monitor",
        parameter: 10 as Parameter,
        unit: "NTU",
        thresholdHigh: 4,
        isActive: true,
      },
    ],
  },
  {
    id: 12,
    organizationId: "org_123",
    name: "Distribution Point 3",
    type: "Distribution",
    location: "East District",
    status: 2 as AssetStatus,
    lastSeen: new Date(Date.now() - 240 * 60000).toISOString(),
    sensors: [
      {
        id: 1201,
        assetId: 12,
        name: "Pressure Gauge",
        parameter: 21 as Parameter,
        unit: "bar",
        thresholdLow: 2,
        thresholdHigh: 6,
        isActive: false,
      },
    ],
  },
];

// Generate 24 hours of readings for sensor 101 (pH)
export const mockReadings: Reading[] = Array.from({ length: 48 }, (_, i) => ({
  sensorId: 101,
  timestamp: new Date(Date.now() - (47 - i) * 30 * 60000).toISOString(),
  value: 7.2 + Math.sin(i / 8) * 0.5 + (Math.random() - 0.5) * 0.2,
  parameter: 1 as Parameter,
}));
